[package]
name = "gggg_ui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fontdue = "0.8.0"
gggg_asset = { path = "../gggg_asset" }
